/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MarketType = IDL.Variant({
  'cryptocurrency' : IDL.Null,
  'forex' : IDL.Null,
  'stocks' : IDL.Null,
  'option' : IDL.Null,
  'future' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Trade = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'marketType' : MarketType,
  'direction' : IDL.Text,
  'stockName' : IDL.Text,
  'emotion' : IDL.Text,
  'date' : IDL.Int,
  'strategy' : IDL.Text,
  'mistakeType' : IDL.Text,
  'followedPlan' : IDL.Bool,
  'target' : IDL.Float64,
  'convictionLevel' : IDL.Nat,
  'stopLoss' : IDL.Float64,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'entryPrice' : IDL.Float64,
  'isAPlusSetup' : IDL.Bool,
  'exitPrice' : IDL.Float64,
  'riskRewardRatio' : IDL.Float64,
});
export const Backup = IDL.Record({
  'trades' : IDL.Vec(Trade),
  'accountSize' : IDL.Float64,
  'dailyMaxLoss' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UpdateTradeRecord = IDL.Record({
  'pnl' : IDL.Float64,
  'emotion' : IDL.Text,
  'strategy' : IDL.Text,
  'target' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTrade' : IDL.Func(
      [
        IDL.Int,
        IDL.Text,
        MarketType,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePnlQuery' : IDL.Func([Trade], [IDL.Float64], ['query']),
  'deleteStrategy' : IDL.Func([IDL.Text], [], []),
  'deleteTrade' : IDL.Func([IDL.Nat], [], []),
  'exportBackup' : IDL.Func([], [Backup], ['query']),
  'getAccountSize' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentTimestamp' : IDL.Func([], [IDL.Int], ['query']),
  'getDailyMaxLoss' : IDL.Func([], [IDL.Float64], ['query']),
  'getRiskStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPnl' : IDL.Float64,
          'accountSize' : IDL.Float64,
          'dailyMaxLoss' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getStrategies' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getTotalTradesCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTradeById' : IDL.Func([IDL.Nat], [IDL.Opt(Trade)], ['query']),
  'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getTradesByStrategy' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importBackup' : IDL.Func([Backup], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveStrategy' : IDL.Func([IDL.Text], [], []),
  'setAccountSize' : IDL.Func([IDL.Float64], [], []),
  'setDailyMaxLoss' : IDL.Func([IDL.Float64], [], []),
  'updateTrade' : IDL.Func([IDL.Nat, UpdateTradeRecord], [IDL.Opt(Trade)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MarketType = IDL.Variant({
    'cryptocurrency' : IDL.Null,
    'forex' : IDL.Null,
    'stocks' : IDL.Null,
    'option' : IDL.Null,
    'future' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Trade = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'marketType' : MarketType,
    'direction' : IDL.Text,
    'stockName' : IDL.Text,
    'emotion' : IDL.Text,
    'date' : IDL.Int,
    'strategy' : IDL.Text,
    'mistakeType' : IDL.Text,
    'followedPlan' : IDL.Bool,
    'target' : IDL.Float64,
    'convictionLevel' : IDL.Nat,
    'stopLoss' : IDL.Float64,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'entryPrice' : IDL.Float64,
    'isAPlusSetup' : IDL.Bool,
    'exitPrice' : IDL.Float64,
    'riskRewardRatio' : IDL.Float64,
  });
  const Backup = IDL.Record({
    'trades' : IDL.Vec(Trade),
    'accountSize' : IDL.Float64,
    'dailyMaxLoss' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UpdateTradeRecord = IDL.Record({
    'pnl' : IDL.Float64,
    'emotion' : IDL.Text,
    'strategy' : IDL.Text,
    'target' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTrade' : IDL.Func(
        [
          IDL.Int,
          IDL.Text,
          MarketType,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePnlQuery' : IDL.Func([Trade], [IDL.Float64], ['query']),
    'deleteStrategy' : IDL.Func([IDL.Text], [], []),
    'deleteTrade' : IDL.Func([IDL.Nat], [], []),
    'exportBackup' : IDL.Func([], [Backup], ['query']),
    'getAccountSize' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentTimestamp' : IDL.Func([], [IDL.Int], ['query']),
    'getDailyMaxLoss' : IDL.Func([], [IDL.Float64], ['query']),
    'getRiskStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPnl' : IDL.Float64,
            'accountSize' : IDL.Float64,
            'dailyMaxLoss' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getStrategies' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getTotalTradesCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTradeById' : IDL.Func([IDL.Nat], [IDL.Opt(Trade)], ['query']),
    'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getTradesByStrategy' : IDL.Func([IDL.Text], [IDL.Vec(Trade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importBackup' : IDL.Func([Backup], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveStrategy' : IDL.Func([IDL.Text], [], []),
    'setAccountSize' : IDL.Func([IDL.Float64], [], []),
    'setDailyMaxLoss' : IDL.Func([IDL.Float64], [], []),
    'updateTrade' : IDL.Func(
        [IDL.Nat, UpdateTradeRecord],
        [IDL.Opt(Trade)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };