/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Backup {
    trades: Array<Trade>;
    accountSize: number;
    dailyMaxLoss: number;
}
export interface UpdateTradeRecord {
    pnl: number;
    emotion: string;
    strategy: string;
    target: number;
    stopLoss: number;
    notes: string;
    entryPrice: number;
}
export interface UserProfile {
    name: string;
}
export interface Trade {
    id: bigint;
    pnl: number;
    marketType: MarketType;
    direction: string;
    stockName: string;
    emotion: string;
    date: bigint;
    strategy: string;
    mistakeType: string;
    followedPlan: boolean;
    target: number;
    convictionLevel: bigint;
    stopLoss: number;
    notes: string;
    quantity: bigint;
    entryPrice: number;
    isAPlusSetup: boolean;
    exitPrice: number;
    riskRewardRatio: number;
}
export enum MarketType {
    cryptocurrency = "cryptocurrency",
    forex = "forex",
    stocks = "stocks",
    option = "option",
    future = "future"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTrade(date: bigint, stockName: string, marketType: MarketType, direction: string, entryPrice: number, exitPrice: number, stopLoss: number, target: number, quantity: bigint, isAPlusSetup: boolean, emotion: string, convictionLevel: bigint, strategy: string, followedPlan: boolean, mistakeType: string, notes: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculatePnlQuery(trade: Trade): Promise<number>;
    deleteStrategy(name: string): Promise<void>;
    deleteTrade(id: bigint): Promise<void>;
    exportBackup(): Promise<Backup>;
    getAccountSize(): Promise<number>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentTimestamp(): Promise<bigint>;
    getDailyMaxLoss(): Promise<number>;
    getRiskStatus(): Promise<{
        totalPnl: number;
        accountSize: number;
        dailyMaxLoss: number;
    }>;
    getStrategies(): Promise<Array<[string, bigint]>>;
    getTotalTradesCount(): Promise<bigint>;
    getTradeById(id: bigint): Promise<Trade | null>;
    getTrades(): Promise<Array<Trade>>;
    getTradesByStrategy(strategy: string): Promise<Array<Trade>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importBackup(backup: Backup): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveStrategy(name: string): Promise<void>;
    setAccountSize(size: number): Promise<void>;
    setDailyMaxLoss(limit: number): Promise<void>;
    updateTrade(tradeId: bigint, update: UpdateTradeRecord): Promise<Trade | null>;
}
import type { Backup as _Backup, MarketType as _MarketType, Trade as _Trade, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTrade(arg0: bigint, arg1: string, arg2: MarketType, arg3: string, arg4: number, arg5: number, arg6: number, arg7: number, arg8: bigint, arg9: boolean, arg10: string, arg11: bigint, arg12: string, arg13: boolean, arg14: string, arg15: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrade(arg0, arg1, to_candid_MarketType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrade(arg0, arg1, to_candid_MarketType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculatePnlQuery(arg0: Trade): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePnlQuery(to_candid_Trade_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePnlQuery(to_candid_Trade_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteStrategy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStrategy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStrategy(arg0);
            return result;
        }
    }
    async deleteTrade(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrade(arg0);
            return result;
        }
    }
    async exportBackup(): Promise<Backup> {
        if (this.processError) {
            try {
                const result = await this.actor.exportBackup();
                return from_candid_Backup_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportBackup();
            return from_candid_Backup_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccountSize(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountSize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountSize();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentTimestamp(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentTimestamp();
            return result;
        }
    }
    async getDailyMaxLoss(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyMaxLoss();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyMaxLoss();
            return result;
        }
    }
    async getRiskStatus(): Promise<{
        totalPnl: number;
        accountSize: number;
        dailyMaxLoss: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskStatus();
            return result;
        }
    }
    async getStrategies(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrategies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrategies();
            return result;
        }
    }
    async getTotalTradesCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalTradesCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalTradesCount();
            return result;
        }
    }
    async getTradeById(arg0: bigint): Promise<Trade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeById(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeById(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrades(): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrades();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrades();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradesByStrategy(arg0: string): Promise<Array<Trade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradesByStrategy(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradesByStrategy(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async importBackup(arg0: Backup): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importBackup(to_candid_Backup_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importBackup(to_candid_Backup_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveStrategy(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStrategy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStrategy(arg0);
            return result;
        }
    }
    async setAccountSize(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccountSize(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccountSize(arg0);
            return result;
        }
    }
    async setDailyMaxLoss(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyMaxLoss(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyMaxLoss(arg0);
            return result;
        }
    }
    async updateTrade(arg0: bigint, arg1: UpdateTradeRecord): Promise<Trade | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrade(arg0, arg1);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrade(arg0, arg1);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Backup_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Backup): Backup {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MarketType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketType): MarketType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Trade_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trade): Trade {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trade]): Trade | null {
    return value.length === 0 ? null : from_candid_Trade_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pnl: number;
    marketType: _MarketType;
    direction: string;
    stockName: string;
    emotion: string;
    date: bigint;
    strategy: string;
    mistakeType: string;
    followedPlan: boolean;
    target: number;
    convictionLevel: bigint;
    stopLoss: number;
    notes: string;
    quantity: bigint;
    entryPrice: number;
    isAPlusSetup: boolean;
    exitPrice: number;
    riskRewardRatio: number;
}): {
    id: bigint;
    pnl: number;
    marketType: MarketType;
    direction: string;
    stockName: string;
    emotion: string;
    date: bigint;
    strategy: string;
    mistakeType: string;
    followedPlan: boolean;
    target: number;
    convictionLevel: bigint;
    stopLoss: number;
    notes: string;
    quantity: bigint;
    entryPrice: number;
    isAPlusSetup: boolean;
    exitPrice: number;
    riskRewardRatio: number;
} {
    return {
        id: value.id,
        pnl: value.pnl,
        marketType: from_candid_MarketType_n12(_uploadFile, _downloadFile, value.marketType),
        direction: value.direction,
        stockName: value.stockName,
        emotion: value.emotion,
        date: value.date,
        strategy: value.strategy,
        mistakeType: value.mistakeType,
        followedPlan: value.followedPlan,
        target: value.target,
        convictionLevel: value.convictionLevel,
        stopLoss: value.stopLoss,
        notes: value.notes,
        quantity: value.quantity,
        entryPrice: value.entryPrice,
        isAPlusSetup: value.isAPlusSetup,
        exitPrice: value.exitPrice,
        riskRewardRatio: value.riskRewardRatio
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trades: Array<_Trade>;
    accountSize: number;
    dailyMaxLoss: number;
}): {
    trades: Array<Trade>;
    accountSize: number;
    dailyMaxLoss: number;
} {
    return {
        trades: from_candid_vec_n9(_uploadFile, _downloadFile, value.trades),
        accountSize: value.accountSize,
        dailyMaxLoss: value.dailyMaxLoss
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cryptocurrency: null;
} | {
    forex: null;
} | {
    stocks: null;
} | {
    option: null;
} | {
    future: null;
}): MarketType {
    return "cryptocurrency" in value ? MarketType.cryptocurrency : "forex" in value ? MarketType.forex : "stocks" in value ? MarketType.stocks : "option" in value ? MarketType.option : "future" in value ? MarketType.future : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trade>): Array<Trade> {
    return value.map((x)=>from_candid_Trade_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Backup_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Backup): _Backup {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_MarketType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketType): _MarketType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Trade_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Trade): _Trade {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trades: Array<Trade>;
    accountSize: number;
    dailyMaxLoss: number;
}): {
    trades: Array<_Trade>;
    accountSize: number;
    dailyMaxLoss: number;
} {
    return {
        trades: to_candid_vec_n20(_uploadFile, _downloadFile, value.trades),
        accountSize: value.accountSize,
        dailyMaxLoss: value.dailyMaxLoss
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    pnl: number;
    marketType: MarketType;
    direction: string;
    stockName: string;
    emotion: string;
    date: bigint;
    strategy: string;
    mistakeType: string;
    followedPlan: boolean;
    target: number;
    convictionLevel: bigint;
    stopLoss: number;
    notes: string;
    quantity: bigint;
    entryPrice: number;
    isAPlusSetup: boolean;
    exitPrice: number;
    riskRewardRatio: number;
}): {
    id: bigint;
    pnl: number;
    marketType: _MarketType;
    direction: string;
    stockName: string;
    emotion: string;
    date: bigint;
    strategy: string;
    mistakeType: string;
    followedPlan: boolean;
    target: number;
    convictionLevel: bigint;
    stopLoss: number;
    notes: string;
    quantity: bigint;
    entryPrice: number;
    isAPlusSetup: boolean;
    exitPrice: number;
    riskRewardRatio: number;
} {
    return {
        id: value.id,
        pnl: value.pnl,
        marketType: to_candid_MarketType_n1(_uploadFile, _downloadFile, value.marketType),
        direction: value.direction,
        stockName: value.stockName,
        emotion: value.emotion,
        date: value.date,
        strategy: value.strategy,
        mistakeType: value.mistakeType,
        followedPlan: value.followedPlan,
        target: value.target,
        convictionLevel: value.convictionLevel,
        stopLoss: value.stopLoss,
        notes: value.notes,
        quantity: value.quantity,
        entryPrice: value.entryPrice,
        isAPlusSetup: value.isAPlusSetup,
        exitPrice: value.exitPrice,
        riskRewardRatio: value.riskRewardRatio
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarketType): {
    cryptocurrency: null;
} | {
    forex: null;
} | {
    stocks: null;
} | {
    option: null;
} | {
    future: null;
} {
    return value == MarketType.cryptocurrency ? {
        cryptocurrency: null
    } : value == MarketType.forex ? {
        forex: null
    } : value == MarketType.stocks ? {
        stocks: null
    } : value == MarketType.option ? {
        option: null
    } : value == MarketType.future ? {
        future: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Trade>): Array<_Trade> {
    return value.map((x)=>to_candid_Trade_n5(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
