/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Backup {
  'trades' : Array<Trade>,
  'accountSize' : number,
  'dailyMaxLoss' : number,
}
export interface Trade {
  'id' : bigint,
  'pnl' : number,
  'direction' : string,
  'stockName' : string,
  'tradeType' : string,
  'emotion' : string,
  'date' : bigint,
  'mistakeType' : string,
  'followedPlan' : boolean,
  'target' : number,
  'convictionLevel' : bigint,
  'stopLoss' : number,
  'notes' : string,
  'quantity' : bigint,
  'entryPrice' : number,
  'isAPlusSetup' : boolean,
  'exitPrice' : number,
  'riskRewardRatio' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTrade' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      bigint,
      boolean,
      string,
      bigint,
      boolean,
      string,
      string,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePnlQuery' : ActorMethod<[Trade], number>,
  'deleteTrade' : ActorMethod<[bigint], undefined>,
  'exportBackup' : ActorMethod<[], Backup>,
  'getAccountSize' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentTimestamp' : ActorMethod<[], bigint>,
  'getDailyMaxLoss' : ActorMethod<[], number>,
  'getRiskStatus' : ActorMethod<
    [],
    { 'totalPnl' : number, 'accountSize' : number, 'dailyMaxLoss' : number }
  >,
  'getTotalTradesCount' : ActorMethod<[], bigint>,
  'getTradeById' : ActorMethod<[bigint], [] | [Trade]>,
  'getTrades' : ActorMethod<[], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importBackup' : ActorMethod<[Backup], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAccountSize' : ActorMethod<[number], undefined>,
  'setDailyMaxLoss' : ActorMethod<[number], undefined>,
  'updateTrade' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      number,
      number,
      number,
      number,
      bigint,
      boolean,
      string,
      bigint,
      boolean,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];